name: who_are_we
description: Who Are We.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependency_overrides: 
  meta: ^1.16.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Pick and read file:
  file_selector: ^1.0.3
  cross_file: ^0.3.0
  utf_ext: ^0.3.3
  file: ^7.0.0
  loop_visitor: ^0.4.0

  # GEDCOM manipulations:
  gedcom_codec: ^0.0.2
  gedcom_structures: ^0.0.2
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
